export default function Loader() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="boxes [&>*:nth-child(1)]:animate-moveBox1 [&>*:nth-child(2)]:animate-moveBox2 [&>*:nth-child(3)]:animate-moveBox3 [&>*:nth-child(4)]:animate-moveBox4 relative mt-[calc(var(--size)*1.5*-1)] h-[calc(var(--size)*2)] w-[calc(var(--size)*3)] [--background:#869EFF] [--duration:800ms] [--size:32px] [transform-origin:_50%_50%] [transform-style:_preserve-3d] [transform:_rotateX(60deg)_rotateZ(45deg)_rotateY(0deg)_translateZ(0px)] [&>*:nth-child(1)]:[transform:_translate(100%,_0)] [&>*:nth-child(2)]:[transform:_translate(0,_100%)] [&>*:nth-child(3)]:[transform:_translate(100%,_100%)] [&>*:nth-child(4)]:[transform:_translate(200%,_0)]">
        <div className="box absolute left-0 top-0 h-[var(--size)] w-[var(--size)] [--bottom:auto] [--left:auto] [--right:auto] [--rotateX:0deg] [--rotateY:0deg] [--top:auto] [--translateZ:calc(var(--size)/2)] [transform-style:_preserve-3d] [&>*:nth-child(1)]:[--left:0] [&>*:nth-child(1)]:[--top:0] [&>*:nth-child(2)]:[--background:#4169E1] [&>*:nth-child(2)]:[--right:0] [&>*:nth-child(2)]:[--rotateY:90deg] [&>*:nth-child(3)]:[--background:#6583FF] [&>*:nth-child(3)]:[--rotateX:-90deg] [&>*:nth-child(4)]:[--background:#D8E3F4] [&>*:nth-child(4)]:[--left:0] [&>*:nth-child(4)]:[--top:0] [&>*:nth-child(4)]:[--translateZ:calc(var(--size)*3*-1)]">
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
        </div>
        <div className="box absolute left-0 top-0 h-[var(--size)] w-[var(--size)] [--bottom:auto] [--left:auto] [--right:auto] [--rotateX:0deg] [--rotateY:0deg] [--top:auto] [--translateZ:calc(var(--size)/2)] [transform-style:_preserve-3d] [&>*:nth-child(1)]:[--left:0] [&>*:nth-child(1)]:[--top:0] [&>*:nth-child(2)]:[--background:#4169E1] [&>*:nth-child(2)]:[--right:0] [&>*:nth-child(2)]:[--rotateY:90deg] [&>*:nth-child(3)]:[--background:#6583FF] [&>*:nth-child(3)]:[--rotateX:-90deg] [&>*:nth-child(4)]:[--background:#D8E3F4] [&>*:nth-child(4)]:[--left:0] [&>*:nth-child(4)]:[--top:0] [&>*:nth-child(4)]:[--translateZ:calc(var(--size)*3*-1)]">
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
        </div>
        <div className="box absolute left-0 top-0 h-[var(--size)] w-[var(--size)] [--bottom:auto] [--left:auto] [--right:auto] [--rotateX:0deg] [--rotateY:0deg] [--top:auto] [--translateZ:calc(var(--size)/2)] [transform-style:_preserve-3d] [&>*:nth-child(1)]:[--left:0] [&>*:nth-child(1)]:[--top:0] [&>*:nth-child(2)]:[--background:#4169E1] [&>*:nth-child(2)]:[--right:0] [&>*:nth-child(2)]:[--rotateY:90deg] [&>*:nth-child(3)]:[--background:#6583FF] [&>*:nth-child(3)]:[--rotateX:-90deg] [&>*:nth-child(4)]:[--background:#D8E3F4] [&>*:nth-child(4)]:[--left:0] [&>*:nth-child(4)]:[--top:0] [&>*:nth-child(4)]:[--translateZ:calc(var(--size)*3*-1)]">
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
        </div>
        <div className="box absolute left-0 top-0 h-[var(--size)] w-[var(--size)] [--bottom:auto] [--left:auto] [--right:auto] [--rotateX:0deg] [--rotateY:0deg] [--top:auto] [--translateZ:calc(var(--size)/2)] [transform-style:_preserve-3d] [&>*:nth-child(1)]:[--left:0] [&>*:nth-child(1)]:[--top:0] [&>*:nth-child(2)]:[--background:#4169E1] [&>*:nth-child(2)]:[--right:0] [&>*:nth-child(2)]:[--rotateY:90deg] [&>*:nth-child(3)]:[--background:#6583FF] [&>*:nth-child(3)]:[--rotateX:-90deg] [&>*:nth-child(4)]:[--background:#D8E3F4] [&>*:nth-child(4)]:[--left:0] [&>*:nth-child(4)]:[--top:0] [&>*:nth-child(4)]:[--translateZ:calc(var(--size)*3*-1)]">
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
          <div className="absolute bottom-[var(--bottom)] left-[var(--left)] right-[var(--right)] top-[var(--top)] h-full w-full [background:var(--background)] [transform:_rotateY(var(--rotateY))_rotateX(var(--rotateX))_translateZ(var(--translateZ))]"></div>
        </div>
      </div>
    </div>
  );
}
